blank_issues_enabled: true
contact_links:
  - name: "â” Ask a Question"
    about: Ask a General Question or start a Discussions.
    url: https://github.com/cssnr/actions-tools/discussions/new?category=q-a

  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about Issues, Features, Questions and More.
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ View the Documentation"
    about: Send General Feedback.
    url: https://intranet.cssnr.com/
