blank_issues_enabled: true
contact_links:
  - name: "â” Ask a Question"
    about: Ask a general question or start a discussion
    url: https://github.com/cssnr/sharex-cli/discussions/new?category=q-a

  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about issues, features, questions and more
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ“ View the Documentation"
    about: Review the documentation and FAQ
    url: https://cssnr.github.io/sharex-cli/
